#?????
server:
  port: 8099
#???????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grad_wygl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

#mybatis plus??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #??mybatis plus ???????????NULL???
      update-strategy: not_empty

#jwt??
jwt:
  secret: com.itmk
  #12????
  expiration: 43200000

#??????url
itmk:
  loginUrl: /api/user/login

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.itmk.web: DEBUG

#logging:

